### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by farodig** [DevExpress-Examples/how-to-use-a-custom-lookup-property-editor-control-for-reference-properties-in-winforms-e1101#2]
Describe code

**Comment by AndreyKozhevnikov** [comment]
Hello,

I added the example's description with the #3 pull request.

If this info is not enough or you have any further question regarding this example, please create a ticket in our <a href='https://www.devexpress.com/Support/Center/Question/Create'>Suppor Center </a>

Thanks,
Andrey
